apiVersion: v1
name: vsphere-cluster-template
description: Cluster template for rke2 on vsphere
version: 0.0.1
annotations:
  catalog.cattle.io/type: cluster-template
  catalog.cattle.io/namespace: fleet-default
