cloudprovider: vsphere

cloudCredentialSecretName: svc-rancher

# Specify nodepool options. Can add multiple node groups, specify etcd, controlplane and worker roles.
nodepools:
- etcd: true
  controlplane: true
  worker: true

  # specify node labels
  labels: {}

  # specify node taints
  taints: {}

  # specify nodepool size
  quantity: 3

  # Pause node pool
  paused: false

  # specify displayName
  # displayName: ""

  # specify rolling update mechanism
  # rollingUpdate:
  #   The maximum number of machines that can be unavailable during the update.
  #   Value can be an absolute number (ex: 5) or a percentage of desired
  #   machines (ex: 10%).
  #   Absolute number is calculated from percentage by rounding down.
  #   This can not be 0 if MaxSurge is 0.
  #   Defaults to 0.
  #   Example: when this is set to 30%, the old MachineSet can be scaled
  #   down to 70% of desired machines immediately when the rolling update
  #   starts. Once new machines are ready, old MachineSet can be scaled
  #   down further, followed by scaling up the new MachineSet, ensuring
  #   that the total number of machines available at all times
  #   during the update is at least 70% of desired machines.
  #   maxUnavailable: "5"
  #   The maximum number of machines that can be scheduled above the
  #   desired number of machines.
  #   Value can be an absolute number (ex: 5) or a percentage of
  #   desired machines (ex: 10%).
  #   This can not be 0 if MaxUnavailable is 0.
  #   Absolute number is calculated from percentage by rounding up.
  #   Defaults to 1.
  #   Example: when this is set to 30%, the new MachineSet can be scaled
  #   up immediately when the rolling update starts, such that the total
  #   number of old and new machines do not exceed 130% of desired
  #   machines. Once old machines have been killed, new MachineSet can
  #   be scaled up further, ensuring that total number of machines running
  #   at any time during the update is at most 130% of desired machines.
  #   maxSurge: "1"

  # specify machineDeployment Labels
  # machineDeploymentLabels: {}

  # specify machineDeployment annotations
  # machineDeploymentAnnotations: {}

  # specify nodepool name
  name: pool-1

  # vSphere vm configuration parameters (used for guestinfo)
  # cfgparam: []

  # If you choose creation type clone a name of what you want to clone is required
  cloneFrom: "Kube_template_Ubu22wcloud-init"

  # Contents of cloud-config yaml file to put into the ISO user-data; Format should be:
  # cloudConfig: |
      #cloud-config
      users:
        - name: node_admin
          shell: /bin/bash
          groups: sudo, admin
          sudo: ['ALL=(ALL) NOPASSWD:ALL']
          ssh-authorized-keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDctSW2GYOQjydMGauEYV6Vb9USxdZRT3XIJBMJACN+e3cNREB1vNX1eKBv0+PGzf9ttTe5/DSLA9M7PZThn1UFJP7NNNNYMdPBySHHK+kJKymPPBGiNOnoiqAO6u1ECuisj1Qg9dDm5RNhE9FPMDYANNzVdvPUCAuH0g/vKiLWX1MxKKDRR6gxkDuGMv3YgRxqhjH9b7cUof3Pas2w85DLGQr4/w+4iw1y8q02LUIRrekhmKnU5dEE6Yita/PBggo6rKw2d5LQdqLzrFnREN/pi7KrkLAr9mSp3PBSNmItC++0nnqU7JFJahJT08PIGwqBJpd6xz57IfjJ9JfhQK2326hoDcWAYsPqTPISN+ePRhH74EH5kTlbijRcBo5qScfkNrVMxFD+6YVBBmEpMQkUK6CUKXBCepY3rUqUScD7zY/dvNwdt+Uben6Pwn0zMqMdubrl2FEv4ikILlSdQIw9CfOq2ztVT+2PD9FZpC1yzBltl3It0N5cQ0XwrEvoC1U= cluster@localhost
      runcmd:
        - [ echo "template cloud-config accessed" >> /tmp/deploy.txt ]
        - [ su echo "10.100.28.102  rancher.devit.eau.jamf.net knode1-dev-rancher.devit.eau.jamf.net" >> /etc/hosts ]
      packages:
        - docker
        - cowsay
      datasource:
        NoCloud:
          # default seedfrom is None
          # if found, then it should contain a url with:
          #    <url>user-data and <url>meta-data
          seedfrom: https://files.jamf.net/server/cloud-init/k8s/eau/

  # vSphere cloud-init filepath or url to add to guestinfo, filepath will be read and base64 encoded before adding
  # cloudinit: ""

  # If you choose to clone from a content library template specify the name of the library
  # contentLibrary: ""

  # vSphere CPU number for docker VM
  cpuCount: "2"

  # 'Creation type when creating a new virtual machine. Supported values: vm, template, library, legacy'
  creationType: "template"

  # vSphere custom attribute, format key/value e.g. '200=mycustom value'
  # customAttribute: ["200=mycustom value"]

  # vSphere datacenter for virtual machine
  datacenter: "EAU"

  # vSphere datastore for virtual machine
  datastore: "eau-pure01_vvol_general"

  # vSphere datastore cluster for virtual machine
  # datastoreCluster: ""

  # vSphere size of disk for docker VM (in MB)
  diskSize: "20480"

  # vSphere folder for the docker VM. This folder must already exist in the datacenter
  folder: "IT/Container Hosts"

  # vSphere compute resource where the docker VM will be instantiated. This can be omitted if using a cluster with DRS
  # hostsystem: ""

  # vSphere size of memory for docker VM (in MB)
  memorySize: "2048"

  # vSphere network where the virtual machine will be attached
  network: "eau-ucs01-it_servers_dev"

  # vSphere resource pool for docker VM
  pool: "host/eau-infrastructure-usc01/Resources"

  # If using a non-B2D image you can specify the ssh port
  sshPort: "22"

  # If using a non-B2D image the uploaded keys will need chown'ed, defaults to staff e.g. docker:staff
  sshUserGroup: staff

  # vSphere tag id e.g. urn:xxx
  tag: ["k8s-zone:zone-a", "pod_storage:eau", "k8s-region:region-us1"]

  # 'vSphere vApp IP allocation policy. Supported values are: dhcp, fixed, transient and fixedAllocated'
  # vappIpallocationpolicy: ""

  # 'vSphere vApp IP protocol for this deployment. Supported values are: IPv4 and IPv6'
  # vappIpprotocol: ""

  # vSphere vApp properties
  # vappProperty: []

  # 'vSphere OVF environment transports to use for properties. Supported values are: iso and com.vmware.guestInfo'
  # vappTransport: ""

  # vSphere IP/hostname for vCenter
  vcenter: "vcenter.jamf.net"

  # vSphere Port for vCenter
  vcenterPort: 443
